name: Lamp Deployment

on:
    workflow_dispatch:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Linting
      uses: ansible-actions/ansible-lint-action@v1.0.3
      with:
       target: |
         ansible/playbook.yml
         ansible/inventory.yml
